// (1)  -> AREA DE UN CIRCULO
// (2)  -> AREA DE UN RECTANGULO
// (3)  -> AREA DE UN CUBO
// (4)  -> FILTRAR SOLO NUMEROS IMPARES
// (5)  -> PARTIR A LA MITAD UNA PALABRA
// (6)  -> MOSTRAR X VECES UNA PALABRA ("hola mundo")
// (7)  -> ORDENAR NUMEROS DE MENOS A MAYOR
// (8)  -> HACIENDO LA LÓGICA DEL LA FUNCIÓN "sort" -> ordenar números (METODO DE BURBUJA)
// (9)  -> INVERTIR UNA PALABRA
// (10) -> DUPLICAR LOS VALORES DEL ARREGLO Y DESPUES SUMARLO
// (11) -> ENCONTRAR PALABRAS QUE RIMEN
// (12) -> BUSCADOR DE PALABRAS
// (13) -> SUMAR LAS EDADES DE LOS USUARIOS MAYORES DE 13 AÑOS
// (14) -> VALIDAR USUARIO (user y password)
// (15) -> RETORNAR LA FECHA EN UN OBJETO { MES, DIA, AÑO}
    let input = "1/25/2021"
    let output = { MES, DIA, AÑO }
// (16) -> ECUCACION ( f(x) = x▼2 + raiz(x) + (x/2) )
// (17) -> ENCRIPTAR Y DESENCRIPTAR PALABRA
