
/* 
    * INPUT -> PROCESAR -> OUTPUT
    * ENTRAS -> PROCESAR -> SALIDA
    * funcion(INPUT) -> const funcion = (INPUT) => { PROCESAR -> return OUTPUT }
*/


// (10) -> DUPLICAR LOS VALORES DEL ARREGLO Y DESPUES SUMARLO
// (11) -> ENCONTRAR PALABRAS QUE RIMEN
// (12) -> BUSCADOR DE PALABRAS
// (14) -> VALIDAR USUARIO (user y password)
// (15) -> RETORNAR LA FECHA EN UN OBJETO { MES, DIA, AÑO}
let input = "1/25/2021"; output = { MES, DIA, AÑO };




